### ISSUE TITLE
[BUG] manual % value input is broken

### ISSUE THREAD

**Issue by K0shachiyamyatA** [FFXIV-CombatReborn/RotationSolverReborn#583]
![Image](https://github.com/user-attachments/assets/ac7921db-9c1f-44dd-bac4-daea84d379f0)

![Image](https://github.com/user-attachments/assets/ee5c4e6f-673e-4ea8-8424-b1e6ab8bc34f)

**Comment by LTS-FFXIV** [comment]
fixed on next version

**Comment by K0shachiyamyatA** [comment]
![Image](https://github.com/user-attachments/assets/ba9ee4fc-43e0-4ba6-9c4e-45309b830c5b)

![Image](https://github.com/user-attachments/assets/046a812c-5f47-4667-9fea-84f1db058bd4)

still broken for me

**Comment by LTS-FFXIV** [comment]
fixed on next version, rotation config percents was handled differently
